# fly.toml app configuration file generated for pysnipster on 2025-07-15T15:46:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pysnipster'
primary_region = 'lhr'

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
