[project]
name = "snipster"
version = "0.1.0"
description = "Intermediate Cohort Project"
readme = "README.md"
authors = [
    { name = "jjeg1979", email = "jjeg1979@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "python-decouple>=3.8",
    "ruff>=0.11.13",
    "sqlmodel>=0.0.24",
]

[project.scripts]
snipster = "snipster:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest-cov>=6.2.1",
]
